apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  selector:
    matchLabels:
      project: t-it-autoscaling
  template:
    metadata:
      labels:
        project: t-it-autoscaling
    spec:
      containers:
        - name: t-it-web-autoscaling
          image: tigunov/k8sphp:v2
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-deployment-autoscaling
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    kind: Deployment
    name: my-web-deployment-autoscaling
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-service
  labels:
    env: prod
    owner: YuriyTigunov
spec:
  selector:
    project: t-it-autoscaling # selecting PODS with those labels
  ports:
    - port: 80 # port on load balancer
      name: app-listener
      protocol: TCP
      targetPort: 80 # port on POD
  type: LoadBalancer