apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-multi
  labels:
    app: my-k8s-deployment-multi
spec:
  replicas: 3
  selector:
    matchLabels:
      project: t-it-multi
  template:
    metadata:
      labels:
        project: t-it-multi
    spec:
      containers:
        - name: t-it-web
          image: tigunov/k8sphp:v2
          ports:
            - containerPort: 80

        - name: tomcat
          image: tomcat
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pods-service
  labels:
    env: prod
    owner: YuriyTigunov
spec:
   type: LoadBalancer
   selector:
     project: t-it-multi
   ports:
     - port: 80
       name: my-web-app-listener
       protocol: TCP
       targetPort: 80

     - port: 8888
       name: tomcat-listener
       protocol: TCP
       targetPort: 8080